name: MP - Build image, push to ECR and scan for vulns

on:
  workflow_call:
    inputs:
      environment:
        description: "Deployment Environment"
        required: false
        type: string
      dockerfile_path:
        description: "Path to build Dockerfile"
        required: false
        type: string
        default: Dockerfile #--Dockerfile in current working directory
      app_name:
        description: "App Name"
        required: true
        type: string
      image_repo:
        description: "ECR Repo Name"
        required: true
        type: string
      image_tag:
        description: "Image Tag"
        required: false
        type: string
        default: ${{ github.sha }}
      image_scan_critical_high_exit_code:
        description: "Error code for image scanner critical/high vulns" #--Set to 0 to allow soft failures
        type: number
        default: 1
    outputs:
      image_registry:
        description: "Image Registry"
        value: ${{ jobs.build_push.outputs.image_registry }}
      image_repo:
        description: "Image Registry"
        value: ${{ jobs.build_push.outputs.image_repo }}
      image_tag:
        description: "Image Registry"
        value: ${{ jobs.build_push.outputs.image_tag }}
      image_uri:
        description: "Image Registry"
        value: ${{ jobs.build_push.outputs.image_uri }}

jobs:
  build_push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: ${{ inputs.environment }}

    steps:
    - name: Git Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #--v6.0.2

    #--Prereq steps https://user-guide.modernisation-platform.service.justice.gov.uk/user-guide/deploying-your-application.html#using-oidc-in-your-application-deployment-pipeline
    - name: ECR Auth
      id: auth
      uses: ministryofjustice/laa-reusable-github-actions/.github/actions/ecr-auth/@main
      with:
        ecr_region: ${{ vars.AWS_REGION }}
        ecr_role: arn:aws:iam::${{ secrets.DEPLOYMENT_ACCOUNT_ID }}:role/modernisation-platform-oidc-cicd
        role-session-name: "github-cicd-${{ inputs.app_name }}-${{ github.run_number }}"
        account_ids: ${{ secrets.ECR_ACCOUNT_ID }}

    - name: Build and Push
      id: build
      uses: ministryofjustice/laa-reusable-github-actions/.github/actions/build-and-push@main
      with:
        dockerfile_path: ${{ inputs.dockerfile_path }}
        image_registry: ${{ steps.auth.outputs.image_registry }}
        image_repo: ${{ inputs.image_repo }}
        image_tag: ${{ inputs.image_tag }}

    - name: Output
      id: output
      run: |
        echo image_registry=${{ steps.build.outputs.image_registry }} >> "$GITHUB_OUTPUT"
        echo image_repo=${{ steps.build.outputs.image_repo }} >> "$GITHUB_OUTPUT"
        echo image_tag=${{ steps.build.outputs.image_tag }} >> "$GITHUB_OUTPUT"
        echo image_uri="${{ steps.build.outputs.image_registry }}/${{ steps.build.outputs.image_repo }}:${{ steps.build.outputs.image_tag }}" >> "$GITHUB_OUTPUT"

    - name: Image Scan
      id: scan-post
      uses: ministryofjustice/laa-reusable-github-actions/.github/actions/image-scan@main
      with:
        image_uri: ${{ steps.output.outputs.image_uri }}
        critical_high_exit_code: ${{ inputs.image_scan_critical_high_exit_code }}

    outputs:
      image_registry: ${{ steps.output.outputs.image_registry }}
      image_repo: ${{ steps.output.outputs.image_repo }}
      image_tag: ${{ steps.output.outputs.image_tag }}
      image_uri: ${{ steps.output.outputs.image_uri }}
